######### Auth #######

@username = "kuntarvishnuprasad41@gmail.com"
@password = "123Kuntar"
@fname = "Vishnu Prasad Kuntar"


### 1. Registration
POST {{host}}/{{version}}/auth/signup
 
Content-Type: application/json

{
    "fname" : {{fname}}
    "username": {{username}},
    "password": {{password}}
}


### 2. SignIn
POST {{host}}/{{version}}/auth/signin
 
Content-Type: application/json

{
    "username": {{username}},
    "password": {{password}}
}


### 3. Buy Course
POST {{host}}/{{version}}/courses/buy
Content-Type: application/json

{
    "courseId" : 1,
    "userId":1
}


### 4.
GET {{host}}/{{version}}/courses/get